# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-12 08:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_type',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='postblog',
            options={'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='stopic',
            options={'verbose_name_plural': '类别'},
        ),
        migrations.AlterField(
            model_name='blog_type',
            name='cname',
            field=models.CharField(max_length=30, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='blg',
            field=models.ManyToManyField(to='postapp.blog_type', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='stic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.stopic', verbose_name='所属类别'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='timedata',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='stopic',
            name='sname',
            field=models.CharField(max_length=30, verbose_name='类别名称'),
        ),
    ]
